---
abstract: 'a modern Curses toolkit'
author:
  - "Damien \"dams\" Krotkine"
generated_by: 'Dist::Zilla version 1.093000'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Curses-Toolkit
provides:
  Curses::Toolkit:
    file: lib/Curses/Toolkit.pm
    version: 0.093060
  Curses::Toolkit::Event:
    file: lib/Curses/Toolkit/Event.pm
    version: 0.093060
  Curses::Toolkit::Event::Focus:
    file: lib/Curses/Toolkit/Event/Focus.pm
    version: 0.093060
  Curses::Toolkit::Event::Focus::In:
    file: lib/Curses/Toolkit/Event/Focus/In.pm
    version: 0.093060
  Curses::Toolkit::Event::Focus::Out:
    file: lib/Curses/Toolkit/Event/Focus/Out.pm
    version: 0.093060
  Curses::Toolkit::Event::Key:
    file: lib/Curses/Toolkit/Event/Key.pm
    version: 0.093060
  Curses::Toolkit::Event::Mouse:
    file: lib/Curses/Toolkit/Event/Mouse.pm
    version: 0.093060
  Curses::Toolkit::Event::Mouse::Click:
    file: lib/Curses/Toolkit/Event/Mouse/Click.pm
    version: 0.093060
  Curses::Toolkit::Event::Shape:
    file: lib/Curses/Toolkit/Event/Shape.pm
    version: 0.093060
  Curses::Toolkit::EventListener:
    file: lib/Curses/Toolkit/EventListener.pm
    version: 0.093060
  Curses::Toolkit::EventListener::Key:
    file: lib/Curses/Toolkit/EventListener/Key.pm
    version: 0.093060
  Curses::Toolkit::Object:
    file: lib/Curses/Toolkit/Object.pm
    version: 0.093060
  Curses::Toolkit::Object::Coordinates:
    file: lib/Curses/Toolkit/Object/Coordinates.pm
    version: 0.093060
  Curses::Toolkit::Object::Flags:
    file: lib/Curses/Toolkit/Object/Flags.pm
    version: 0.093060
  Curses::Toolkit::Object::Shape:
    file: lib/Curses/Toolkit/Object/Shape.pm
    version: 0.093060
  Curses::Toolkit::Role:
    file: lib/Curses/Toolkit/Role.pm
    version: 0.093060
  Curses::Toolkit::Role::Focusable:
    file: lib/Curses/Toolkit/Role/Focusable.pm
    version: 0.093060
  Curses::Toolkit::Signal:
    file: lib/Curses/Toolkit/Signal.pm
    version: 0.093060
  Curses::Toolkit::Signal::Clicked:
    file: lib/Curses/Toolkit/Signal/Clicked.pm
    version: 0.093060
  Curses::Toolkit::Signal::Focused:
    file: lib/Curses/Toolkit/Signal/Focused.pm
    version: 0.093060
  Curses::Toolkit::Theme:
    file: lib/Curses/Toolkit/Theme.pm
    version: 0.093060
  Curses::Toolkit::Theme::Default:
    file: lib/Curses/Toolkit/Theme/Default.pm
    version: 0.093060
  Curses::Toolkit::Theme::Default::Color:
    file: lib/Curses/Toolkit/Theme/Default/Color.pm
    version: 0.093060
  Curses::Toolkit::Theme::Default::Color::Pink:
    file: lib/Curses/Toolkit/Theme/Default/Color/Pink.pm
    version: 0.093060
  Curses::Toolkit::Theme::Default::Color::Yellow:
    file: lib/Curses/Toolkit/Theme/Default/Color/Yellow.pm
    version: 0.093060
  Curses::Toolkit::Widget:
    file: lib/Curses/Toolkit/Widget.pm
    version: 0.093060
  Curses::Toolkit::Widget::Bin:
    file: lib/Curses/Toolkit/Widget/Bin.pm
    version: 0.093060
  Curses::Toolkit::Widget::Border:
    file: lib/Curses/Toolkit/Widget/Border.pm
    version: 0.093060
  Curses::Toolkit::Widget::Button:
    file: lib/Curses/Toolkit/Widget/Button.pm
    version: 0.093060
  Curses::Toolkit::Widget::Container:
    file: lib/Curses/Toolkit/Widget/Container.pm
    version: 0.093060
  Curses::Toolkit::Widget::Entry:
    file: lib/Curses/Toolkit/Widget/Entry.pm
    version: 0.093060
  Curses::Toolkit::Widget::GenericButton:
    file: lib/Curses/Toolkit/Widget/GenericButton.pm
    version: 0.093060
  Curses::Toolkit::Widget::HBox:
    file: lib/Curses/Toolkit/Widget/HBox.pm
    version: 0.093060
  Curses::Toolkit::Widget::HPaned:
    file: lib/Curses/Toolkit/Widget/HPaned.pm
    version: 0.093060
  Curses::Toolkit::Widget::HScrollBar:
    file: lib/Curses/Toolkit/Widget/HScrollBar.pm
    version: 0.093060
  Curses::Toolkit::Widget::Label:
    file: lib/Curses/Toolkit/Widget/Label.pm
    version: 0.093060
  Curses::Toolkit::Widget::Paned:
    file: lib/Curses/Toolkit/Widget/Paned.pm
    version: 0.093060
  Curses::Toolkit::Widget::VBox:
    file: lib/Curses/Toolkit/Widget/VBox.pm
    version: 0.093060
  Curses::Toolkit::Widget::VPaned:
    file: lib/Curses/Toolkit/Widget/VPaned.pm
    version: 0.093060
  Curses::Toolkit::Widget::VScrollBar:
    file: lib/Curses/Toolkit/Widget/VScrollBar.pm
    version: 0.093060
  Curses::Toolkit::Widget::Window:
    file: lib/Curses/Toolkit/Widget/Window.pm
    version: 0.093060
  Curses::Toolkit::Widget::Window::Dialog:
    file: lib/Curses/Toolkit/Widget/Window/Dialog.pm
    version: 0.093060
  Curses::Toolkit::Widget::Window::Dialog::About:
    file: lib/Curses/Toolkit/Widget/Window/Dialog/About.pm
    version: 0.093060
  POE::Component::Curses:
    file: lib/POE/Component/Curses.pm
    version: 0.093060
  POE::Component::Curses::MainLoop:
    file: lib/POE/Component/Curses/MainLoop.pm
    version: 0.093060
requires:
  Curses: 0
  Curses::UI: 0
  English: 0
  File::Find: 0
  FindBin: 0
  List::MoreUtils: 0
  List::Util: 0
  POE: 0
  Params::Validate: 0
  Test::More: 0
  Tie::Array::Iterable: 0
  UNIVERSAL::require: 0.13
  overload: 0
  parent: 0
resources:
  homepage: http://search.cpan.org/dist/Curses-Toolkit
  repository: http://github.com/dams/curses-toolkit
version: 0.093060
